namespace App_TobiiSpec
{
    partial class MainForm
    {

        #region Source codes generated by Windows form designer
        private void InitializeComponent()
        {
            this._mainMenu = new System.Windows.Forms.MenuStrip();
            this._fileMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._fileExitMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._controlMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._controlStartMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._toolMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._toolFindMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._toolCalibrationMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._toolConfigMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._tobiiSelectGroupbox = new System.Windows.Forms.GroupBox();
            this._tobiiSearchButton = new System.Windows.Forms.Button();
            this._tobiiSelectCombobox = new System.Windows.Forms.ComboBox();
            this._startButton = new System.Windows.Forms.Button();
            this._mainMenu.SuspendLayout();
            this._tobiiSelectGroupbox.SuspendLayout();
            this.SuspendLayout();
            //
            // _mainMenu
            //
            this._mainMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._fileMenu,
            this._controlMenu,
            this._toolMenu});
            this._mainMenu.Location = new System.Drawing.Point(0, 0);
            this._mainMenu.Name = "_mainMenu";
            this._mainMenu.Size = new System.Drawing.Size(579, 24);
            this._mainMenu.TabIndex = 0;
            this._mainMenu.Text = "menuStrip1";
            //
            // _fileMenu
            //
            this._fileMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._fileExitMenu});
            this._fileMenu.Name = "_fileMenu";
            this._fileMenu.Size = new System.Drawing.Size(70, 20);
            this._fileMenu.Text = "File (&F)";
            //
            // _fileExitMenu
            //
            this._fileExitMenu.Name = "_fileExitMenu";
            this._fileExitMenu.Size = new System.Drawing.Size(116, 22);
            this._fileExitMenu.Text = "Finish (&X)";
            this._fileExitMenu.Click += new System.EventHandler(this._fileExitMenu_Click);
            //
            // _controlMenu
            //
            this._controlMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._controlStartMenu});
            this._controlMenu.Name = "_controlMenu";
            this._controlMenu.Size = new System.Drawing.Size(61, 20);
            this._controlMenu.Text = "Control (&C)";
            //
            // _controlStartMenu
            //
            this._controlStartMenu.Name = "_controlStartMenu";
            this._controlStartMenu.Size = new System.Drawing.Size(144, 22);
            this._controlStartMenu.Text = "Start / Finish (&S)";
            this._controlStartMenu.Click += new System.EventHandler(this._controlStartMenu_Click);
            //
            // _toolMenu
            //
            this._toolMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._toolFindMenu,
            this._toolCalibrationMenu,
            this._toolConfigMenu});
            this._toolMenu.Name = "_toolMenu";
            this._toolMenu.Size = new System.Drawing.Size(63, 20);
            this._toolMenu.Text = "Tool (&T)";
            //
            // _toolFindMenu
            //
            this._toolFindMenu.Name = "_toolFindMenu";
            this._toolFindMenu.Size = new System.Drawing.Size(169, 22);
            this._toolFindMenu.Text = "Search Tobii (&F)";
            this._toolFindMenu.Click += new System.EventHandler(this._toolFindMenu_Click);
            //
            // _toolCalibrationMenu
            //
            this._toolCalibrationMenu.Name = "_toolCalibrationMenu";
            this._toolCalibrationMenu.Size = new System.Drawing.Size(169, 22);
            this._toolCalibrationMenu.Text = "Calibration (&C)";
            this._toolCalibrationMenu.Click += new System.EventHandler(this._toolCalibrationMenu_Click);
            //
            // _toolConfigMenu
            //
            this._toolConfigMenu.Name = "_toolConfigMenu";
            this._toolConfigMenu.Size = new System.Drawing.Size(169, 22);
            this._toolConfigMenu.Text = "Settings (&S)";
            this._toolConfigMenu.Click += new System.EventHandler(this._toolConfigMenu_Click);
            //
            // _tobiiSelectGroupbox
            //
            this._tobiiSelectGroupbox.Controls.Add(this._tobiiSearchButton);
            this._tobiiSelectGroupbox.Controls.Add(this._tobiiSelectCombobox);
            this._tobiiSelectGroupbox.Location = new System.Drawing.Point(12, 27);
            this._tobiiSelectGroupbox.Name = "_tobiiSelectGroupbox";
            this._tobiiSelectGroupbox.Size = new System.Drawing.Size(555, 63);
            this._tobiiSelectGroupbox.TabIndex = 1;
            this._tobiiSelectGroupbox.TabStop = false;
            this._tobiiSelectGroupbox.Text = "&Select Tobii Pro Spectrum";
            //
            // _tobiiSearchButton
            //
            this._tobiiSearchButton.Location = new System.Drawing.Point(449, 22);
            this._tobiiSearchButton.Name = "_tobiiSearchButton";
            this._tobiiSearchButton.Size = new System.Drawing.Size(97, 23);
            this._tobiiSearchButton.TabIndex = 1;
            this._tobiiSearchButton.Text = "Search Tobii (&F)";
            this._tobiiSearchButton.UseVisualStyleBackColor = true;
            this._tobiiSearchButton.Click += new System.EventHandler(this._toolFindMenu_Click);
            //
            // _tobiiSelectCombobox
            //
            this._tobiiSelectCombobox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this._tobiiSelectCombobox.FormattingEnabled = true;
            this._tobiiSelectCombobox.Location = new System.Drawing.Point(16, 24);
            this._tobiiSelectCombobox.Name = "_tobiiSelectCombobox";
            this._tobiiSelectCombobox.Size = new System.Drawing.Size(427, 20);
            this._tobiiSelectCombobox.TabIndex = 0;
            this._tobiiSelectCombobox.SelectedIndexChanged += new System.EventHandler(this._tobiiSelectCombobox_SelectedIndexChanged);
            //
            // _startButton
            //
            this._startButton.Location = new System.Drawing.Point(402, 96);
            this._startButton.Name = "_startButton";
            this._startButton.Size = new System.Drawing.Size(156, 48);
            this._startButton.TabIndex = 2;
            this._startButton.Text = "Start (&S)";
            this._startButton.UseVisualStyleBackColor = true;
            this._startButton.Click += new System.EventHandler(this._controlStartMenu_Click);
            //
            // MainForm
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(579, 159);
            this.Controls.Add(this._startButton);
            this.Controls.Add(this._tobiiSelectGroupbox);
            this.Controls.Add(this._mainMenu);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MainMenuStrip = this._mainMenu;
            this.MaximizeBox = false;
            this.Name = "MainForm";
            this.Text = "App-Tobii Spectrum";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.MainForm_FormClosed);
            this._mainMenu.ResumeLayout(false);
            this._mainMenu.PerformLayout();
            this._tobiiSelectGroupbox.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion

        private System.Windows.Forms.MenuStrip _mainMenu;
        private System.Windows.Forms.GroupBox _tobiiSelectGroupbox;
        private System.Windows.Forms.ComboBox _tobiiSelectCombobox;
        private System.Windows.Forms.Button _tobiiSearchButton;
        private System.Windows.Forms.Button _startButton;
        private System.Windows.Forms.ToolStripMenuItem _fileMenu;
        private System.Windows.Forms.ToolStripMenuItem _fileExitMenu;
        private System.Windows.Forms.ToolStripMenuItem _toolMenu;
        private System.Windows.Forms.ToolStripMenuItem _toolFindMenu;
        private System.Windows.Forms.ToolStripMenuItem _toolCalibrationMenu;
        private System.Windows.Forms.ToolStripMenuItem _toolConfigMenu;
        private System.Windows.Forms.ToolStripMenuItem _controlMenu;
        private System.Windows.Forms.ToolStripMenuItem _controlStartMenu;
    }
}

