namespace App_WebCam
{
    partial class MainForm
    {
        /// <summary>
        /// Necessary designer variable
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up the using resources
        /// </summary>
        /// <param name="disposing">Select true when destroying the managed resource and false for others</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Source codes generated by Windows form designer

        /// <summary>
        /// Necessary method for designer support. Do not edit inside code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this._framePictBox = new System.Windows.Forms.PictureBox();
            this._backgroundWorker = new System.ComponentModel.BackgroundWorker();
            this._recBtn = new System.Windows.Forms.Button();
            this._stopBtn = new System.Windows.Forms.Button();
            this._viewBtn = new System.Windows.Forms.Button();
            this._rootPanel = new System.Windows.Forms.TableLayoutPanel();
            this._controlPanel = new System.Windows.Forms.Panel();
            this._setVideFileBtn = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this._videoFilePathBox = new System.Windows.Forms.TextBox();
            this._lslNameLabel = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this._framePictBox)).BeginInit();
            this._rootPanel.SuspendLayout();
            this._controlPanel.SuspendLayout();
            this.SuspendLayout();
            //
            // _framePictBox
            //
            this._framePictBox.Anchor = System.Windows.Forms.AnchorStyles.None;
            this._framePictBox.BackColor = System.Drawing.Color.White;
            this._framePictBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._framePictBox.Location = new System.Drawing.Point(3, 83);
            this._framePictBox.Name = "_framePictBox";
            this._framePictBox.Size = new System.Drawing.Size(640, 480);
            this._framePictBox.TabIndex = 0;
            this._framePictBox.TabStop = false;
            //
            // _backgroundWorker
            //
            this._backgroundWorker.WorkerReportsProgress = true;
            this._backgroundWorker.WorkerSupportsCancellation = true;
            this._backgroundWorker.DoWork += new System.ComponentModel.DoWorkEventHandler(this._backgroundWorker_DoWork);
            this._backgroundWorker.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this._backgroundWorker_ProgressChanged);
            this._backgroundWorker.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this._backgroundWorker_RunWorkerCompleted);
            //
            // _recBtn
            //
            this._recBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this._recBtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._recBtn.Location = new System.Drawing.Point(468, 45);
            this._recBtn.Name = "_recBtn";
            this._recBtn.Size = new System.Drawing.Size(75, 23);
            this._recBtn.TabIndex = 4;
            this._recBtn.Text = "Rec (R)";
            this._recBtn.UseVisualStyleBackColor = false;
            this._recBtn.Click += new System.EventHandler(this._recBtn_Click);
            //
            // _stopBtn
            //
            this._stopBtn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(255)))));
            this._stopBtn.Enabled = false;
            this._stopBtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._stopBtn.Location = new System.Drawing.Point(557, 45);
            this._stopBtn.Name = "_stopBtn";
            this._stopBtn.Size = new System.Drawing.Size(75, 23);
            this._stopBtn.TabIndex = 5;
            this._stopBtn.Text = "Stop (&S)";
            this._stopBtn.UseVisualStyleBackColor = false;
            this._stopBtn.Click += new System.EventHandler(this._stopBtn_Click);
            //
            // _viewBtn
            //
            this._viewBtn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this._viewBtn.Location = new System.Drawing.Point(376, 45);
            this._viewBtn.Name = "_viewBtn";
            this._viewBtn.Size = new System.Drawing.Size(75, 23);
            this._viewBtn.TabIndex = 3;
            this._viewBtn.Text = "View (&V)";
            this._viewBtn.UseVisualStyleBackColor = true;
            this._viewBtn.Click += new System.EventHandler(this._viewBtn_Click);
            //
            // _rootPanel
            //
            this._rootPanel.ColumnCount = 1;
            this._rootPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this._rootPanel.Controls.Add(this._controlPanel, 0, 0);
            this._rootPanel.Controls.Add(this._framePictBox, 0, 1);
            this._rootPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this._rootPanel.Location = new System.Drawing.Point(0, 0);
            this._rootPanel.Name = "_rootPanel";
            this._rootPanel.RowCount = 2;
            this._rootPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 80F));
            this._rootPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this._rootPanel.Size = new System.Drawing.Size(647, 567);
            this._rootPanel.TabIndex = 5;
            //
            // _controlPanel
            //
            this._controlPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._controlPanel.Controls.Add(this._setVideFileBtn);
            this._controlPanel.Controls.Add(this.label2);
            this._controlPanel.Controls.Add(this._videoFilePathBox);
            this._controlPanel.Controls.Add(this._lslNameLabel);
            this._controlPanel.Controls.Add(this._viewBtn);
            this._controlPanel.Controls.Add(this._stopBtn);
            this._controlPanel.Controls.Add(this._recBtn);
            this._controlPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this._controlPanel.Location = new System.Drawing.Point(1, 0);
            this._controlPanel.Margin = new System.Windows.Forms.Padding(1, 0, 1, 0);
            this._controlPanel.Name = "_controlPanel";
            this._controlPanel.Size = new System.Drawing.Size(645, 80);
            this._controlPanel.TabIndex = 0;
            //
            // _setVideFileBtn
            //
            this._setVideFileBtn.Location = new System.Drawing.Point(330, 27);
            this._setVideFileBtn.Name = "_setVideFileBtn";
            this._setVideFileBtn.Size = new System.Drawing.Size(24, 24);
            this._setVideFileBtn.TabIndex = 1;
            this._setVideFileBtn.Text = "...";
            this._setVideFileBtn.UseVisualStyleBackColor = true;
            this._setVideFileBtn.Click += new System.EventHandler(this._selectVideFileBtn_Click);
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(15, 12);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(82, 12);
            this.label2.TabIndex = 8;
            this.label2.Text = "Video file path:";
            //
            // _videoFilePathBox
            //
            this._videoFilePathBox.Location = new System.Drawing.Point(15, 28);
            this._videoFilePathBox.Multiline = true;
            this._videoFilePathBox.Name = "_videoFilePathBox";
            this._videoFilePathBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this._videoFilePathBox.Size = new System.Drawing.Size(309, 40);
            this._videoFilePathBox.TabIndex = 0;
            //
            // _lslNameLabel
            //
            this._lslNameLabel.AutoSize = true;
            this._lslNameLabel.Location = new System.Drawing.Point(374, 17);
            this._lslNameLabel.Name = "_lslNameLabel";
            this._lslNameLabel.Size = new System.Drawing.Size(57, 12);
            this._lslNameLabel.TabIndex = 6;
            this._lslNameLabel.Text = "LSL name:";
            //
            // MainForm
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(647, 567);
            this.Controls.Add(this._rootPanel);
            this.MinimumSize = new System.Drawing.Size(663, 606);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "App-WebCam";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            ((System.ComponentModel.ISupportInitialize)(this._framePictBox)).EndInit();
            this._rootPanel.ResumeLayout(false);
            this._controlPanel.ResumeLayout(false);
            this._controlPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PictureBox _framePictBox;
        private System.ComponentModel.BackgroundWorker _backgroundWorker;
        private System.Windows.Forms.Button _recBtn;
        private System.Windows.Forms.Button _stopBtn;
        private System.Windows.Forms.Button _viewBtn;
        private System.Windows.Forms.TableLayoutPanel _rootPanel;
        private System.Windows.Forms.Panel _controlPanel;
        private System.Windows.Forms.Button _setVideFileBtn;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox _videoFilePathBox;
        private System.Windows.Forms.Label _lslNameLabel;
    }
}

