//------------------------------------------------------------------------------
// <auto-generated>
//     The source code were generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Editing this file might lead to error when executing or regenerating the code.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_WebCam.Properties
{
    using System;


    /// <summary>
    ///   Resource class for searching localized string. The data type is strictly defined.
    /// </summary>
    // This class is auto-generated by tools such as ResGen or Visual Studio from StronglyTypedResourceBuilder.
    // To add or delete the member, edit the .ResX file and execute ResGen with the \str options or rebuild the visual studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Return the ResourceManager instance that is cached in this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App_WebCam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Override the CurrentUICulture property of current thread in every case.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
