namespace LslLeapMotion
{
    partial class MainForm
    {
        /// <summary>
        /// Necessary designer variable
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up the using resources
        /// </summary>
        /// <param name="disposing">Select true when destroying the managed resource and false for others</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Source codes generated by Windows form designer

        /// <summary>
        /// Necessary method for designer support. Do not edit inside code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this._mainMenu = new System.Windows.Forms.MenuStrip();
            this._fileMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._fileExitMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._toolMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._toolSettingMenu = new System.Windows.Forms.ToolStripMenuItem();
            this._startButton = new System.Windows.Forms.Button();
            this._statusLabel = new System.Windows.Forms.Label();
            this._mainMenu.SuspendLayout();
            this.SuspendLayout();
            //
            // _mainMenu
            //
            this._mainMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._fileMenu,
            this._toolMenu});
            this._mainMenu.Location = new System.Drawing.Point(0, 0);
            this._mainMenu.Name = "_mainMenu";
            this._mainMenu.Size = new System.Drawing.Size(675, 24);
            this._mainMenu.TabIndex = 2;
            this._mainMenu.Text = "menuStrip1";
            //
            // _fileMenu
            //
            this._fileMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._fileExitMenu});
            this._fileMenu.Name = "_fileMenu";
            this._fileMenu.Size = new System.Drawing.Size(70, 20);
            this._fileMenu.Text = "File (&F)";
            //
            // _fileExitMenu
            //
            this._fileExitMenu.Name = "_fileExitMenu";
            this._fileExitMenu.Size = new System.Drawing.Size(116, 22);
            this._fileExitMenu.Text = "Finish (&X)";
            this._fileExitMenu.Click += new System.EventHandler(this._fileExitMenu_Click);
            //
            // _toolMenu
            //
            this._toolMenu.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this._toolSettingMenu});
            this._toolMenu.Name = "_toolMenu";
            this._toolMenu.Size = new System.Drawing.Size(63, 20);
            this._toolMenu.Text = "Tool (&T)";
            //
            // _toolSettingMenu
            //
            this._toolSettingMenu.Name = "_toolSettingMenu";
            this._toolSettingMenu.Size = new System.Drawing.Size(115, 22);
            this._toolSettingMenu.Text = "Settings (&S)";
            this._toolSettingMenu.Click += new System.EventHandler(this._toolSettingMenu_Click);
            //
            // _startButton
            //
            this._startButton.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            this._startButton.Location = new System.Drawing.Point(12, 27);
            this._startButton.Name = "_startButton";
            this._startButton.Size = new System.Drawing.Size(162, 63);
            this._startButton.TabIndex = 3;
            this._startButton.Text = "Start (&S)";
            this._startButton.UseVisualStyleBackColor = true;
            this._startButton.Click += new System.EventHandler(this._startButton_Click);
            //
            // _statusLabel
            //
            this._statusLabel.Font = new System.Drawing.Font("MS UI Gothic", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            this._statusLabel.Location = new System.Drawing.Point(180, 27);
            this._statusLabel.Name = "_statusLabel";
            this._statusLabel.Size = new System.Drawing.Size(483, 63);
            this._statusLabel.TabIndex = 4;
            this._statusLabel.Text = "-";
            this._statusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            //
            // MainForm
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(675, 100);
            this.Controls.Add(this._statusLabel);
            this.Controls.Add(this._startButton);
            this.Controls.Add(this._mainMenu);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MainMenuStrip = this._mainMenu;
            this.Name = "MainForm";
            this.Text = "Leap Motion";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this._mainMenu.ResumeLayout(false);
            this._mainMenu.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.MenuStrip _mainMenu;
        private System.Windows.Forms.ToolStripMenuItem _fileMenu;
        private System.Windows.Forms.ToolStripMenuItem _fileExitMenu;
        private System.Windows.Forms.ToolStripMenuItem _toolMenu;
        private System.Windows.Forms.ToolStripMenuItem _toolSettingMenu;
        private System.Windows.Forms.Button _startButton;
        private System.Windows.Forms.Label _statusLabel;
    }
}

